In [2]:
import numpy as np

In [3]:
a_list = [1, 2, 3]
a_array = np.array(a_list)

In [4]:
print(type(a_list))
print(type(a_array))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
a_2D = np.array(matrix)

In [6]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [11]:
np.random.uniform(0, 1, 5)

array([0.91996812, 0.30282889, 0.24561324, 0.74340724, 0.59419837])

In [12]:
np.random.randn(2,2)

array([[-0.3538734 , -0.01437759],
       [ 2.35368194, -0.24357656]])

In [13]:
mu, sigma = 1, 0.5
np.random.normal(mu, sigma, size = (3, 2))

array([[0.92075384, 0.95559866],
       [0.14010004, 0.16558102],
       [1.30044322, 0.67593613]])

In [14]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[ 1.41885369,  0.5868707 ],
        [-0.65093037,  2.64449721]],

       [[ 1.20239562,  2.4269864 ],
        [ 0.54462128,  1.83929214]],

       [[ 0.94095667,  1.80389656],
        [ 0.18694716,  2.22195839]]])

In [15]:
np.random.randint(1, 100, 5)

array([ 5, 88,  3, 93, 55], dtype=int32)

In [16]:
np.random.seed(0)

In [17]:
arr = np.arange(0, 10)
arr_r = arr.reshape(2, 5)
print('arr: ')
print(arr)
print('arr_r: ')
print(arr_r)

arr: 
[0 1 2 3 4 5 6 7 8 9]
arr_r: 
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
my_arr = np.random.randint(1, 100, 10)
print(my_arr)

[45 48 65 68 68 10 84 22 37 88]


In [19]:
my_arr.max()

np.int32(88)

In [20]:
my_arr.argmax()

np.int64(9)

In [22]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

In [23]:
arr_1 + arr_2

array([5, 7, 9])

In [24]:
arr_1 * arr_2

array([ 4, 10, 18])

In [25]:
np.exp(arr_1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [26]:
np.log(arr_1)

array([0.        , 0.69314718, 1.09861229])