In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.4'

In [3]:
p_list = [1, 2, 3]
p_list

[1, 2, 3]

In [4]:
np_1d = np.array(p_list)
np_1d

array([1, 2, 3])

In [5]:
type(p_list)

list

In [6]:
type(np_1d)

numpy.ndarray

In [7]:
p_matrix = [[1,2,3],[4,5,6],[7,8,9]]
p_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np_matrix = np.array(p_matrix)
np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
rng = np.random.default_rng()
rng.random()

0.9125848184725647

In [15]:
np.random.uniform(0, 1, 10)

array([0.01561854, 0.31408748, 0.97846402, 0.44217767, 0.35650266,
       0.87365236, 0.94471655, 0.30901703, 0.01989051, 0.68295052])

In [16]:
np.random.randn(2,2)

array([[-2.9517924 ,  1.64416919],
       [-1.22380642, -1.54100033]])

In [17]:
mu, sigma = 1, 0.5
np.random.normal(mu, sigma, size = (3, 2))

array([[0.4035189 , 0.44065268],
       [0.68741028, 1.1531521 ],
       [1.39078645, 0.86730827]])

In [18]:
mean = [1, 2]
cov = [[1, 0], [0, 1]]
np.random.multivariate_normal(mean, cov, size= (3, 2))

array([[[ 2.70795138,  2.27725584],
        [ 1.70541788,  1.54870242]],

       [[ 1.91387954,  1.75341   ],
        [ 0.04353085, -0.16763379]],

       [[ 0.05506795,  2.01924026],
        [ 1.94346831,  2.52176895]]])

In [19]:
np.random.randint(1, 100, 5)

array([53, 35, 51, 30, 69], dtype=int32)

In [20]:
np.random.seed(0)

In [21]:
a1d = np.arange(0, 10)
a1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a2d = a1d.reshape(2, 5)
a2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
xs = np.random.randint(1, 100, 10)
xs

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88], dtype=int32)

In [24]:
xs.mean()

np.float64(53.5)

In [25]:
xs.max()

np.int32(88)

In [26]:
xs.argmax()

np.int64(9)

In [27]:
xs1 = np.array([1, 2, 3])
xs2 = np.array([4, 5, 6])

In [28]:
xs1 + xs2

array([5, 7, 9])

In [29]:
xs1 * xs2

array([ 4, 10, 18])

In [30]:
np.exp(xs1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [31]:
np.log(xs1)

array([0.        , 0.69314718, 1.09861229])